const express = require("express");
const authMiddleware = require("../Middlewares/auth-middleware");
const { requireAdmin, requireSuperAdmin, requirePermission } = require("../Middlewares/admin-middleware");
const { exportCustomersCsv } = require("../Controllers/user-controller");
const { getAgingProducts, getProductAnalytics } = require("../Controllers/product-controller");
const { getOrderInvoice } = require("../Controllers/order-controller");
const { validateObjectIdParam } = require("../Middlewares/request-validation");
const { globalSearch } = require("../Controllers/admin-search-controller");
const adminLogMiddleware = require("../Middlewares/admin-log-middleware");
const {
    salesAnalytics,
    productsAnalytics,
    dropsAnalytics,
    customersAnalytics,
    reviewsAnalytics,
} = require("../Controllers/analytics-controller");
const {
    getAllRecommendations,
    getRecommendationByType,
    regenerateRecommendation,
} = require("../Controllers/recommendations-controller");
const {
    getAdminNotifications,
    getAdminNotification,
    updateNotification,
    deleteNotification,
    sendAdminMessage,
} = require("../Controllers/notification-controller");
const {
    createCategory,
    updateCategory,
    deleteCategory,
} = require("../Controllers/category-controller");

const router = express.Router();

router.get("/search", authMiddleware, requireAdmin, globalSearch);

router.get("/users/export", authMiddleware, requireSuperAdmin, exportCustomersCsv);
router.get(
    "/products/aging",
    authMiddleware,
    requireAdmin,
    requirePermission("products"),
    getAgingProducts
);
router.get(
    "/products/:id/analytics",
    authMiddleware,
    requireAdmin,
    requirePermission("products"),
    getProductAnalytics
);
router.get(
    "/orders/:id/invoice",
    authMiddleware,
    requireAdmin,
    requirePermission("orders"),
    validateObjectIdParam("id", "order id"),
    getOrderInvoice
);

// Admin analytics (restored module)
router.get(
    "/analytics/sales",
    authMiddleware,
    requireAdmin,
    requirePermission("viewAnalytics"),
    salesAnalytics
);
router.get(
    "/analytics/products",
    authMiddleware,
    requireAdmin,
    requirePermission("viewAnalytics"),
    productsAnalytics
);
router.get(
    "/analytics/drops",
    authMiddleware,
    requireAdmin,
    requirePermission("viewAnalytics"),
    dropsAnalytics
);
router.get(
    "/analytics/customers",
    authMiddleware,
    requireAdmin,
    requirePermission("viewAnalytics"),
    customersAnalytics
);
router.get(
    "/analytics/reviews",
    authMiddleware,
    requireAdmin,
    requirePermission("viewAnalytics"),
    reviewsAnalytics
);

// AI insights / recommendations (generated by the nightly Claude cron)
router.get(
    "/recommendations",
    authMiddleware,
    requireAdmin,
    requirePermission("viewAnalytics"),
    getAllRecommendations
);
router.get(
    "/recommendations/:type",
    authMiddleware,
    requireAdmin,
    requirePermission("viewAnalytics"),
    getRecommendationByType
);
router.post(
    "/recommendations/:type/regenerate",
    authMiddleware,
    requireAdmin,
    requirePermission("viewAnalytics"),
    adminLogMiddleware,
    regenerateRecommendation
);

// Admin notification center. `broadcast` is registered before the :id routes
// so the literal path isn't captured by the :id param.
router.get(
    "/notifications",
    authMiddleware,
    requireAdmin,
    requirePermission("notifications"),
    getAdminNotifications
);
router.post(
    "/notifications/broadcast",
    authMiddleware,
    requireAdmin,
    requirePermission("sendCampaigns"),
    adminLogMiddleware,
    sendAdminMessage
);
router.get(
    "/notifications/:id",
    authMiddleware,
    requireAdmin,
    requirePermission("notifications"),
    validateObjectIdParam("id", "notification id"),
    getAdminNotification
);
router.patch(
    "/notifications/:id",
    authMiddleware,
    requireAdmin,
    requirePermission("notifications"),
    validateObjectIdParam("id", "notification id"),
    adminLogMiddleware,
    updateNotification
);
router.delete(
    "/notifications/:id",
    authMiddleware,
    requireAdmin,
    requirePermission("notifications"),
    validateObjectIdParam("id", "notification id"),
    adminLogMiddleware,
    deleteNotification
);

// Admin category management
router.post(
    "/categories",
    authMiddleware,
    requireAdmin,
    requirePermission("products"),
    createCategory
);

router.put(
    "/categories/:id",
    authMiddleware,
    requireAdmin,
    requirePermission("products"),
    validateObjectIdParam("id", "category id"),
    updateCategory
);

router.delete(
    "/categories/:id",
    authMiddleware,
    requireAdmin,
    requirePermission("products"),
    validateObjectIdParam("id", "category id"),
    deleteCategory
);

module.exports = router;
