import axiosInstance from "@/api/axiosInstance";

// AI insight streams generated by the nightly OpenAI cron. axiosInstance
// attaches the Bearer token + baseURL (v1 API), so paths are relative.
export const fetchRecommendationApi = (type) =>
  axiosInstance.get(`/admin/recommendations/${type}`);

export const fetchAllRecommendationsApi = () =>
  axiosInstance.get(`/admin/recommendations`);

export const regenerateRecommendationApi = (type) =>
  axiosInstance.post(`/admin/recommendations/${type}/regenerate`);
