const path = require("path");
const dotenv = require("dotenv");

dotenv.config({ path: path.resolve(__dirname, ".env.test") });

const TEST_DB_URI =
  process.env.MONGODB_TEST_URI || "mongodb://127.0.0.1:27017/saga_elite_test";

// Force the seed script (which reads MONGO_DB_URI) to use the test database.
process.env.MONGO_DB_URI = TEST_DB_URI;
process.env.NODE_ENV = "test";

const COLLECTIONS_TO_RESET = [
  "users",
  "products",
  "orders",
  "reviews",
  "drops",
  "coupons",
  "usercoupons",
  "smartalerts",
  "adminlogs",
  "notifications",
  "manualpayments",
  "newslettersubscribers",
  "contacts",
  "carts",
  "wishlists",
];

const dropCollections = async (mongoose) => {
  const conn = mongoose.connection;
  for (const name of COLLECTIONS_TO_RESET) {
    try {
      await conn.db.collection(name).deleteMany({});
    } catch (err) {
      // Collection may not exist on a fresh DB — ignore.
      if (!/ns not found/i.test(String(err.message))) {
        console.warn(`[e2e setup] could not clear ${name}:`, err.message);
      }
    }
  }
};

const seedFixtures = async (mongoose) => {
  // Minimum fixtures so navigable tests have content. Add only what's needed
  // for smoke tests; per-feature tests can seed their own state.
  const Product = require(path.resolve(
    __dirname,
    "../Server-side/Models/Product.js"
  ));
  const Drop = require(path.resolve(
    __dirname,
    "../Server-side/Models/Drop.js"
  ));

  await Product.create([
    {
      name: "E2E Sample Tee",
      artNo: "E2E-TEE-001",
      brand: "Saga Elite",
      category: "Unisex",
      basePrice: 4500,
      variants: [
        { sku: "E2E-TEE-001-S-BLK", size: "S", color: "Black", stock: 10 },
        { sku: "E2E-TEE-001-M-BLK", size: "M", color: "Black", stock: 8 },
      ],
    },
    {
      name: "E2E Low Stock Hoodie",
      artNo: "E2E-HOOD-002",
      brand: "Saga Elite",
      category: "Unisex",
      basePrice: 8900,
      lowStockThreshold: 5,
      cartAddCount: 3,
      variants: [
        { sku: "E2E-HOOD-002-M-NAV", size: "M", color: "Navy", stock: 2 },
      ],
    },
  ]);

  // Drop with a future release date so /admin/drops has content.
  await Drop.create({
    name: "E2E Drop Sample",
    description: "Generated by Playwright global-setup",
    releaseDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
    isPublished: false,
  });
};

module.exports = async () => {
  const mongoose = require(path.resolve(
    __dirname,
    "../Server-side/node_modules/mongoose"
  ));

  console.log("[e2e setup] connecting to", TEST_DB_URI);
  await mongoose.connect(TEST_DB_URI);

  console.log("[e2e setup] resetting collections");
  await dropCollections(mongoose);

  await mongoose.disconnect();

  // Run seed-demo-admins as a black box (it manages its own connection).
  const { seedDemoAdmins } = require(path.resolve(
    __dirname,
    "../Server-side/scripts/seed-demo-admins.js"
  ));
  console.log("[e2e setup] seeding demo admins");
  await seedDemoAdmins();

  // Reconnect to add fixtures.
  await mongoose.connect(TEST_DB_URI);
  console.log("[e2e setup] seeding test fixtures");
  await seedFixtures(mongoose);
  await mongoose.disconnect();

  console.log("[e2e setup] complete");
};
